### ISSUE TITLE
roboai package - No model / New models confusion

### ISSUE THREAD

**Issue by FSamina** [robo-ai/roboai-python-cli#34]
@martasls
bot model is not being packaged when deployed
https://drive.google.com/drive/folders/1yrkqLa51Etbs2rSexKjttxEOAXZ6iOZx?usp=sharing

by: @marisacastanho

**Comment by FSamina** [comment]
![Screenshot from 2021-02-03 14-51-13](https://user-images.githubusercontent.com/25133907/106764313-95f09480-662f-11eb-80ab-6cd58ddad02a.png)
<Original Ticket>

**Comment by FSamina** [comment]
New models are being generated without training.
Steps:

1. download voicebot-20210203T142509Z-001.zip && extract
2. run roboai package
A new model should appear inside the models folder

![image](https://user-images.githubusercontent.com/25133907/106764991-4199e480-6630-11eb-9ecc-e8f3fd436c1a.png)

**Comment by FSamina** [comment]
![image_2021_02_03T11_41_04_770Z](https://user-images.githubusercontent.com/25133907/106782798-7fa00400-6642-11eb-8a3d-24c25a627b85.png)
Original screenshot

**Comment by martasls** [comment]
As discussed, no new model is being generated. The problem with the deployment is because of the backslashes used in windows. Fix in progress.
