### ISSUE TITLE
When we call for train or shell/run actions can we double check that all the requirement.txt are installed

### ISSUE THREAD

**Issue by FSamina** [robo-ai/roboai-python-cli#37]
Different bots will use different versions of the lib of modules and different external modules. So it will be easier to manage if the requirements were automatically checked before their possible usage.

**Comment by martasls** [comment]
I think there's a potential problem with this which is if we're installing packages from a git repo (for example), the requirement will look different than the installed package (tbc) and thus it will mislead the user.
