### ISSUE TITLE
Use 'rasa data convert' to get a json of the nlu instead of reading the file

### ISSUE THREAD

**Issue by martasls** [robo-ai/roboai-python-cli#44]
Right now the nlu file is being read to build an nlu dataframe. This is prone to error because the file may contain comments etc which are being dealt but it's possible that not all possibilities have been covered. Furthermore if we use rasa data convert utility we're not dependent on the file type (markdown vs yaml for Rasa 2)

**Comment by FSamina** [comment]
Tracked in JIRA (ROBO-1789)
